apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vkcikfgks-python
  janus-idp.io/tekton: vkcikfgks-python
  backstage.io/kubernetes-id: vkcikfgks-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vkcikfgks-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
